
export const PROVIDER_TOKEN = {
  USER_SERVICE: Symbol('USER_SERVICE'),
  AUTH_SERVICE: Symbol('AUTH_SERVICE'),
  FILE_SERVICE: Symbol('FILE_SERVICE'),
  CUSTOM_USER_DETAILS_SERVICE: Symbol('CUSTOM_USER_DETAILS_SERVICE'),
  PERMISSION_SERVICE: Symbol('PERMISSION_SERVICE'),
  ROLE_SERVICE: Symbol('ROLE_SERVICE'),
  CATEGORY_SERVICE: Symbol('CATEGORY_SERVICE'),
  INVENTORY_SERVICE: Symbol('INVENTORY_SERVICE'),
  RECOMMENDATION_SERVICE: Symbol('RECOMMENDATION_SERVICE'),
  PRODUCT_SERVICE: Symbol('PRODUCT_SERVICE'),
  PRODUCT_IMAGE_SERVICE: Symbol('PRODUCT_IMAGE_SERVICE'),
  PET_SERVICE: Symbol('PET_SERVICE'),
  CART_SERVICE: Symbol('CART_SERVICE'),
  CART_ITEM_SERVICE: Symbol('CART_ITEM_SERVICE'),

  PRODUCT_REVIEW_SERVICE: Symbol('PRODUCT_REVIEW_SERVICE'),
  PET_SERVICE_REVIEW_SERVICE: Symbol('PET_SERVICE_REVIEW_SERVICE'),

  PET_SERVICE_SERVICE: Symbol('PET_SERVICE_SERVICE'),
  PET_SERVICE_IMAGE_SERVICE: Symbol('PET_SERVICE_IMAGE_SERVICE'),

  ORDER_SERVICE: Symbol('ORDER_SERVICE'),
  SHIPPING_ADDRESS_SERVICE: Symbol('SHIPPING_ADDRESS_SERVICE'),
  BOOKING_SERVICE: Symbol('BOOKING_SERVICE'),
  MENU_SERVICE: Symbol('MENU_SERVICE'),
} as const;

